FROM jjanzic/docker-python3-opencv:opencv-4.0.0

COPY ./requirements.txt /root/py-cv-utils/requirements.txt
RUN pip3 install -r /root/py-cv-utils/requirements.txt

COPY . /root/py-cv-utils
WORKDIR /root/py-cv-utils

ENTRYPOINT ["python3", "-m", "unittest", "discover"]
